import { Attorney, PracticeArea, BlogPost, Matter, TimeEntry, Invoice, DashboardMetrics, Task } from "./types";

export const practiceAreas: PracticeArea[] = [
  {
    slug: "corporate-law",
    title: "Corporate Law",
    shortDescription: "Strategic counsel for businesses of all sizes, from startups to Fortune 500 companies.",
    description: "Our Corporate Law team provides comprehensive legal services to businesses at every stage of growth. We advise on entity formation, corporate governance, mergers and acquisitions, joint ventures, and regulatory compliance. Our attorneys have deep experience in structuring complex transactions and protecting our clients' interests in competitive markets.",
    icon: "Building2",
    features: ["Mergers & Acquisitions", "Corporate Governance", "Entity Formation", "Securities Compliance", "Joint Ventures", "Private Equity"],
  },
  {
    slug: "litigation",
    title: "Litigation",
    shortDescription: "Aggressive advocacy in courtrooms and boardrooms across the country.",
    description: "When disputes arise, Largify Lawship's Litigation team delivers aggressive, strategic representation. We handle complex commercial disputes, employment litigation, intellectual property battles, and appellate work. Our trial-tested attorneys have a proven track record of achieving favorable outcomes through both negotiation and courtroom advocacy.",
    icon: "Gavel",
    features: ["Commercial Disputes", "Employment Litigation", "Appellate Practice", "Class Actions", "Arbitration & Mediation", "IP Litigation"],
  },
  {
    slug: "family-law",
    title: "Family Law",
    shortDescription: "Compassionate guidance through life's most personal legal matters.",
    description: "Our Family Law attorneys understand that family legal matters are deeply personal. We provide compassionate yet effective representation in divorce, child custody, adoption, and prenuptial agreements. We prioritize mediation and collaborative approaches while always being prepared to advocate forcefully in court when necessary.",
    icon: "Heart",
    features: ["Divorce & Separation", "Child Custody & Support", "Adoption", "Prenuptial Agreements", "Domestic Violence Protection", "Guardianship"],
  },
  {
    slug: "estate-planning",
    title: "Estate Planning",
    shortDescription: "Protect your legacy and provide for future generations with confidence.",
    description: "Largify Lawship's Estate Planning team helps clients protect their assets and ensure their wishes are honored. We draft wills, establish trusts, create advance directives, and develop comprehensive estate plans tailored to each client's unique situation. Our attorneys also handle probate administration and estate litigation.",
    icon: "Shield",
    features: ["Wills & Trusts", "Probate Administration", "Tax Planning", "Asset Protection", "Advance Directives", "Charitable Giving"],
  },
  {
    slug: "real-estate",
    title: "Real Estate",
    shortDescription: "Full-service real estate counsel for commercial and residential transactions.",
    description: "From commercial developments to residential closings, our Real Estate practice provides full-service legal counsel. We handle purchase and sale agreements, lease negotiations, title issues, zoning matters, and real estate litigation. Our attorneys ensure smooth transactions and protect our clients' property interests.",
    icon: "Home",
    features: ["Commercial Transactions", "Residential Closings", "Lease Negotiations", "Zoning & Land Use", "Title Insurance", "Construction Law"],
  },
  {
    slug: "intellectual-property",
    title: "Intellectual Property",
    shortDescription: "Safeguard your innovations, brands, and creative works.",
    description: "Our Intellectual Property attorneys protect the creative assets and innovations that drive business value. We handle patent prosecution and litigation, trademark registration and enforcement, copyright protection, and trade secret matters. We help clients build and defend strong IP portfolios.",
    icon: "Lightbulb",
    features: ["Patent Prosecution", "Trademark Registration", "Copyright Protection", "Trade Secrets", "IP Licensing", "IP Litigation"],
  },
];

export const attorneys: Attorney[] = [
  {
    id: "1",
    name: "Margaret Chen",
    title: "Managing Partner",
    email: "m.chen@largifylawship.com",
    phone: "(555) 100-2001",
    photo: "/attorneys/chen.jpg",
    bio: "Margaret Chen founded Largify Lawship with a vision to create a modern, client-centric law firm. With over 25 years of experience in corporate law and M&A, she has led transactions totaling over $5 billion. Margaret is recognized by Chambers USA and Super Lawyers for her exceptional work in corporate governance.",
    specialties: ["Corporate Law", "Mergers & Acquisitions", "Securities"],
    barAdmissions: ["New York", "California", "District of Columbia"],
    education: ["J.D., Harvard Law School", "B.A., Yale University"],
    awards: ["Chambers USA Leading Individual", "Super Lawyers Top 50 Women", "Best Lawyers in America"],
  },
  {
    id: "2",
    name: "James Okafor",
    title: "Senior Partner, Litigation",
    email: "j.okafor@largifylawship.com",
    phone: "(555) 100-2002",
    photo: "/attorneys/okafor.jpg",
    bio: "James Okafor is a nationally recognized trial attorney with a career spanning two decades. He has tried over 100 cases to verdict and achieved landmark results in commercial litigation, employment disputes, and class actions. James is known for his commanding courtroom presence and meticulous case preparation.",
    specialties: ["Commercial Litigation", "Employment Law", "Class Actions"],
    barAdmissions: ["New York", "New Jersey", "Connecticut"],
    education: ["J.D., Columbia Law School", "B.A., Howard University"],
    awards: ["National Trial Lawyers Top 100", "Benchmark Litigation Star", "ABA Pro Bono Award"],
  },
  {
    id: "3",
    name: "Sofia Ramirez",
    title: "Partner, Family Law",
    email: "s.ramirez@largifylawship.com",
    phone: "(555) 100-2003",
    photo: "/attorneys/ramirez.jpg",
    bio: "Sofia Ramirez brings warmth and strategic thinking to every family law case. With 15 years of experience, she is an expert mediator and collaborative law practitioner who prioritizes finding solutions that protect children and preserve family relationships. When litigation is necessary, Sofia is a fierce advocate.",
    specialties: ["Family Law", "Mediation", "Child Custody"],
    barAdmissions: ["New York", "Florida"],
    education: ["J.D., NYU School of Law", "B.A., Georgetown University"],
    awards: ["Super Lawyers Rising Star", "AAML Fellow", "Top Family Lawyer - NY Magazine"],
  },
  {
    id: "4",
    name: "William Hartford",
    title: "Partner, Estate Planning",
    email: "w.hartford@largifylawship.com",
    phone: "(555) 100-2004",
    photo: "/attorneys/hartford.jpg",
    bio: "William Hartford has spent his career helping families protect their legacies. As a board-certified specialist in estate planning and trust law, he creates sophisticated plans that minimize tax exposure and ensure seamless wealth transfer. William also handles complex probate litigation and trust disputes.",
    specialties: ["Estate Planning", "Tax Law", "Probate"],
    barAdmissions: ["New York", "Massachusetts"],
    education: ["J.D., Georgetown University Law Center", "LL.M. in Taxation, NYU", "B.A., Boston College"],
    awards: ["AV Preeminent Rating", "ACTEC Fellow", "Best Lawyers - Trusts and Estates"],
  },
  {
    id: "5",
    name: "Aisha Patel",
    title: "Partner, Real Estate",
    email: "a.patel@largifylawship.com",
    phone: "(555) 100-2005",
    photo: "/attorneys/patel.jpg",
    bio: "Aisha Patel is a leading real estate attorney who has closed over $2 billion in commercial transactions. She advises developers, investors, and lenders on all aspects of real estate law, from land acquisition to complex financing structures. Aisha is also an adjunct professor at Columbia Law School.",
    specialties: ["Real Estate", "Commercial Transactions", "Construction Law"],
    barAdmissions: ["New York", "California"],
    education: ["J.D., Stanford Law School", "B.S., MIT"],
    awards: ["Real Estate Board of NY Rising Star", "CREW Network Impact Award"],
  },
  {
    id: "6",
    name: "David Kim",
    title: "Partner, Intellectual Property",
    email: "d.kim@largifylawship.com",
    phone: "(555) 100-2006",
    photo: "/attorneys/kim.jpg",
    bio: "David Kim combines a deep technical background with sharp legal acumen. Before law school, he was a software engineer at Google. Now he leverages that experience to protect innovations in technology, biotechnology, and creative industries. David has successfully prosecuted over 500 patents.",
    specialties: ["Patent Law", "Technology", "Trade Secrets"],
    barAdmissions: ["New York", "USPTO Patent Bar"],
    education: ["J.D., UC Berkeley School of Law", "M.S. Computer Science, Stanford", "B.S. Computer Science, Caltech"],
    awards: ["IAM Patent 1000", "Managing IP Rising Star", "LMG Life Sciences Star"],
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "understanding-business-formation",
    title: "Understanding Business Formation: LLC vs. Corporation",
    excerpt: "Choosing the right business entity is one of the most important decisions an entrepreneur will make. Here's what you need to know.",
    content: "",
    author: "Margaret Chen",
    date: "2026-02-28",
    category: "Corporate Law",
    image: "/blog/business-formation.jpg",
    readTime: "8 min read",
  },
  {
    slug: "protecting-your-ip",
    title: "5 Steps to Protecting Your Intellectual Property",
    excerpt: "In the digital age, your ideas are your most valuable asset. Learn how to protect them from the moment of conception.",
    content: "",
    author: "David Kim",
    date: "2026-02-20",
    category: "Intellectual Property",
    image: "/blog/ip-protection.jpg",
    readTime: "6 min read",
  },
  {
    slug: "estate-planning-essentials",
    title: "Estate Planning Essentials: What Every Family Needs",
    excerpt: "It's never too early to start planning your estate. Here are the essential documents and strategies every family should have.",
    content: "",
    author: "William Hartford",
    date: "2026-02-15",
    category: "Estate Planning",
    image: "/blog/estate-planning.jpg",
    readTime: "10 min read",
  },
  {
    slug: "navigating-child-custody",
    title: "Navigating Child Custody: A Parent's Guide",
    excerpt: "Child custody decisions are among the most emotionally challenging aspects of divorce. Understanding the process can help.",
    content: "",
    author: "Sofia Ramirez",
    date: "2026-02-10",
    category: "Family Law",
    image: "/blog/child-custody.jpg",
    readTime: "7 min read",
  },
  {
    slug: "commercial-lease-negotiation",
    title: "10 Critical Points in Commercial Lease Negotiation",
    excerpt: "Don't sign a commercial lease without understanding these crucial negotiation points that could save your business thousands.",
    content: "",
    author: "Aisha Patel",
    date: "2026-02-05",
    category: "Real Estate",
    image: "/blog/commercial-lease.jpg",
    readTime: "9 min read",
  },
  {
    slug: "litigation-preparation",
    title: "How to Prepare for Litigation: What Clients Should Know",
    excerpt: "If you're facing a lawsuit, preparation is key. Here's a comprehensive guide to what you can expect and how to get ready.",
    content: "",
    author: "James Okafor",
    date: "2026-01-28",
    category: "Litigation",
    image: "/blog/litigation-prep.jpg",
    readTime: "11 min read",
  },
];

export const sampleMatters: Matter[] = [
  {
    id: "M-2026-001",
    caseNumber: "NX-2026-0142",
    title: "TechCorp Acquisition of StartupXYZ",
    clientId: "C-001",
    clientName: "TechCorp Industries",
    assignedAttorneyId: "1",
    assignedAttorneyName: "Margaret Chen",
    practiceArea: "Corporate Law",
    status: "active",
    priority: "high",
    openDate: "2026-01-15",
    description: "Advising TechCorp on the $45M acquisition of StartupXYZ, including due diligence, deal structuring, and regulatory compliance.",
    tasks: [],
    notes: [],
  },
  {
    id: "M-2026-002",
    caseNumber: "NX-2026-0143",
    title: "Henderson v. Global Manufacturing",
    clientId: "C-002",
    clientName: "Global Manufacturing LLC",
    assignedAttorneyId: "2",
    assignedAttorneyName: "James Okafor",
    practiceArea: "Litigation",
    status: "active",
    priority: "urgent",
    openDate: "2025-11-03",
    description: "Defending Global Manufacturing in a wrongful termination class action brought by former employees at the Detroit facility.",
    courtName: "U.S. District Court, Eastern District of Michigan",
    opposingCounsel: "Smith & Associates",
    tasks: [],
    notes: [],
  },
  {
    id: "M-2026-003",
    caseNumber: "NX-2026-0144",
    title: "Martinez Divorce Proceedings",
    clientId: "C-003",
    clientName: "Elena Martinez",
    assignedAttorneyId: "3",
    assignedAttorneyName: "Sofia Ramirez",
    practiceArea: "Family Law",
    status: "active",
    priority: "medium",
    openDate: "2026-02-01",
    description: "Representing Elena Martinez in divorce proceedings, including property division, child custody arrangements, and spousal support.",
    courtName: "New York County Family Court",
    tasks: [],
    notes: [],
  },
  {
    id: "M-2026-004",
    caseNumber: "NX-2026-0145",
    title: "Whitfield Estate Plan",
    clientId: "C-004",
    clientName: "Robert & Alice Whitfield",
    assignedAttorneyId: "4",
    assignedAttorneyName: "William Hartford",
    practiceArea: "Estate Planning",
    status: "open",
    priority: "medium",
    openDate: "2026-02-20",
    description: "Comprehensive estate plan for the Whitfield family including revocable trusts, charitable giving strategies, and tax minimization.",
    tasks: [],
    notes: [],
  },
  {
    id: "M-2026-005",
    caseNumber: "NX-2026-0146",
    title: "Apex Tower Development",
    clientId: "C-005",
    clientName: "Apex Developers Inc.",
    assignedAttorneyId: "5",
    assignedAttorneyName: "Aisha Patel",
    practiceArea: "Real Estate",
    status: "active",
    priority: "high",
    openDate: "2025-10-15",
    description: "Representing Apex Developers in a $120M mixed-use tower development including land acquisition, financing, and zoning approvals.",
    tasks: [],
    notes: [],
  },
  {
    id: "M-2026-006",
    caseNumber: "NX-2026-0147",
    title: "NovaTech Patent Portfolio",
    clientId: "C-006",
    clientName: "NovaTech Solutions",
    assignedAttorneyId: "6",
    assignedAttorneyName: "David Kim",
    practiceArea: "Intellectual Property",
    status: "active",
    priority: "medium",
    openDate: "2026-01-05",
    description: "Prosecuting a portfolio of 12 patent applications related to NovaTech's AI-powered healthcare diagnostics platform.",
    tasks: [],
    notes: [],
  },
];

export const sampleTasks: Task[] = [
  { id: "T-001", matterId: "M-2026-001", title: "Complete due diligence review", description: "Review all financial documents for StartupXYZ", assignedTo: "Margaret Chen", dueDate: "2026-03-15", status: "in-progress", priority: "high" },
  { id: "T-002", matterId: "M-2026-001", title: "Draft acquisition agreement", description: "Prepare first draft of acquisition agreement", assignedTo: "Margaret Chen", dueDate: "2026-03-25", status: "pending", priority: "high" },
  { id: "T-003", matterId: "M-2026-002", title: "Prepare motion to dismiss", description: "Draft and file motion to dismiss class certification", assignedTo: "James Okafor", dueDate: "2026-03-10", status: "in-progress", priority: "urgent" },
  { id: "T-004", matterId: "M-2026-002", title: "Depose lead plaintiff", description: "Schedule and conduct deposition", assignedTo: "James Okafor", dueDate: "2026-03-20", status: "pending", priority: "high" },
  { id: "T-005", matterId: "M-2026-003", title: "File custody motion", description: "Prepare and file motion for temporary custody arrangement", assignedTo: "Sofia Ramirez", dueDate: "2026-03-12", status: "completed", priority: "medium" },
  { id: "T-006", matterId: "M-2026-004", title: "Draft revocable trust", description: "Prepare revocable living trust documents", assignedTo: "William Hartford", dueDate: "2026-03-18", status: "pending", priority: "medium" },
  { id: "T-007", matterId: "M-2026-005", title: "Review zoning application", description: "Final review of zoning variance application", assignedTo: "Aisha Patel", dueDate: "2026-03-08", status: "overdue", priority: "high" },
  { id: "T-008", matterId: "M-2026-006", title: "Respond to office action", description: "Prepare response to USPTO office action on Patent App #3", assignedTo: "David Kim", dueDate: "2026-03-22", status: "pending", priority: "medium" },
];

export const sampleTimeEntries: TimeEntry[] = [
  { id: "TE-001", matterId: "M-2026-001", matterTitle: "TechCorp Acquisition", attorneyId: "1", attorneyName: "Margaret Chen", date: "2026-03-08", hours: 3.5, description: "Reviewed due diligence materials and financial statements", billable: true, rate: 650, status: "approved" },
  { id: "TE-002", matterId: "M-2026-001", matterTitle: "TechCorp Acquisition", attorneyId: "1", attorneyName: "Margaret Chen", date: "2026-03-07", hours: 2.0, description: "Conference call with client re: acquisition timeline", billable: true, rate: 650, status: "approved" },
  { id: "TE-003", matterId: "M-2026-002", matterTitle: "Henderson v. Global Mfg", attorneyId: "2", attorneyName: "James Okafor", date: "2026-03-08", hours: 5.0, description: "Drafted motion to dismiss class certification", billable: true, rate: 600, status: "draft" },
  { id: "TE-004", matterId: "M-2026-002", matterTitle: "Henderson v. Global Mfg", attorneyId: "2", attorneyName: "James Okafor", date: "2026-03-07", hours: 1.5, description: "Legal research on class action precedent in 6th Circuit", billable: true, rate: 600, status: "approved" },
  { id: "TE-005", matterId: "M-2026-003", matterTitle: "Martinez Divorce", attorneyId: "3", attorneyName: "Sofia Ramirez", date: "2026-03-08", hours: 2.0, description: "Prepared custody motion and supporting declarations", billable: true, rate: 500, status: "approved" },
  { id: "TE-006", matterId: "M-2026-005", matterTitle: "Apex Tower Development", attorneyId: "5", attorneyName: "Aisha Patel", date: "2026-03-08", hours: 4.0, description: "Drafted purchase and sale agreement for land parcel", billable: true, rate: 575, status: "approved" },
  { id: "TE-007", matterId: "M-2026-006", matterTitle: "NovaTech Patent Portfolio", attorneyId: "6", attorneyName: "David Kim", date: "2026-03-07", hours: 3.0, description: "Drafted patent claims for healthcare diagnostics application", billable: true, rate: 550, status: "approved" },
  { id: "TE-008", matterId: "M-2026-004", matterTitle: "Whitfield Estate Plan", attorneyId: "4", attorneyName: "William Hartford", date: "2026-03-06", hours: 2.5, description: "Client meeting to discuss estate planning goals and asset inventory", billable: true, rate: 525, status: "billed" },
];

export const sampleInvoices: Invoice[] = [
  {
    id: "INV-001",
    invoiceNumber: "NX-INV-2026-0089",
    matterId: "M-2026-001",
    matterTitle: "TechCorp Acquisition of StartupXYZ",
    clientId: "C-001",
    clientName: "TechCorp Industries",
    issueDate: "2026-03-01",
    dueDate: "2026-03-31",
    items: [
      { description: "Legal services - Due diligence review (Feb 2026)", hours: 28, rate: 650, amount: 18200 },
      { description: "Legal services - Contract drafting (Feb 2026)", hours: 12, rate: 650, amount: 7800 },
    ],
    subtotal: 26000,
    tax: 0,
    total: 26000,
    status: "sent",
  },
  {
    id: "INV-002",
    invoiceNumber: "NX-INV-2026-0090",
    matterId: "M-2026-002",
    matterTitle: "Henderson v. Global Manufacturing",
    clientId: "C-002",
    clientName: "Global Manufacturing LLC",
    issueDate: "2026-03-01",
    dueDate: "2026-03-31",
    items: [
      { description: "Legal services - Motion practice (Feb 2026)", hours: 35, rate: 600, amount: 21000 },
      { description: "Legal services - Discovery (Feb 2026)", hours: 20, rate: 600, amount: 12000 },
      { description: "Court filing fees", hours: 0, rate: 0, amount: 450 },
    ],
    subtotal: 33450,
    tax: 0,
    total: 33450,
    status: "paid",
    paidDate: "2026-03-10",
  },
  {
    id: "INV-003",
    invoiceNumber: "NX-INV-2026-0091",
    matterId: "M-2026-005",
    matterTitle: "Apex Tower Development",
    clientId: "C-005",
    clientName: "Apex Developers Inc.",
    issueDate: "2026-02-01",
    dueDate: "2026-03-03",
    items: [
      { description: "Legal services - Zoning review (Jan 2026)", hours: 22, rate: 575, amount: 12650 },
      { description: "Legal services - Construction contracts (Jan 2026)", hours: 18, rate: 575, amount: 10350 },
    ],
    subtotal: 23000,
    tax: 0,
    total: 23000,
    status: "overdue",
  },
  {
    id: "INV-004",
    invoiceNumber: "NX-INV-2026-0092",
    matterId: "M-2026-004",
    matterTitle: "Whitfield Estate Plan",
    clientId: "C-004",
    clientName: "Robert & Alice Whitfield",
    issueDate: "2026-03-05",
    dueDate: "2026-04-04",
    items: [
      { description: "Legal services - Estate planning consultation (Feb 2026)", hours: 8, rate: 525, amount: 4200 },
    ],
    subtotal: 4200,
    tax: 0,
    total: 4200,
    status: "draft",
  },
];

export const dashboardMetrics: DashboardMetrics = {
  totalMatters: 47,
  activeMatters: 32,
  billableHoursThisMonth: 1247,
  revenueThisMonth: 385000,
  outstandingInvoices: 156000,
  upcomingDeadlines: 18,
  newClientsThisMonth: 7,
  collectionRate: 92.4,
};

export const monthlyRevenue = [
  { month: "Sep", revenue: 310000, target: 350000 },
  { month: "Oct", revenue: 345000, target: 350000 },
  { month: "Nov", revenue: 298000, target: 350000 },
  { month: "Dec", revenue: 275000, target: 350000 },
  { month: "Jan", revenue: 362000, target: 375000 },
  { month: "Feb", revenue: 390000, target: 375000 },
  { month: "Mar", revenue: 385000, target: 375000 },
];

export const practiceAreaRevenue = [
  { name: "Corporate Law", value: 142000, color: "#1e40af" },
  { name: "Litigation", value: 98000, color: "#dc2626" },
  { name: "Family Law", value: 45000, color: "#d97706" },
  { name: "Estate Planning", value: 38000, color: "#059669" },
  { name: "Real Estate", value: 42000, color: "#7c3aed" },
  { name: "IP", value: 20000, color: "#0891b2" },
];

export const attorneyPerformance = [
  { name: "M. Chen", billableHours: 168, target: 160, realization: 95 },
  { name: "J. Okafor", billableHours: 172, target: 160, realization: 92 },
  { name: "S. Ramirez", billableHours: 145, target: 150, realization: 88 },
  { name: "W. Hartford", billableHours: 138, target: 140, realization: 94 },
  { name: "A. Patel", billableHours: 155, target: 150, realization: 91 },
  { name: "D. Kim", billableHours: 162, target: 155, realization: 96 },
];
